export const imagensPerguntas = [
    './img/imagem-container-verde.jpg',
    './img/youon-home.jpg',
    './img/container-cinza.jpg',
    './img/image-5.jpeg',
    './img/image-6.jpeg',
    './img/image-7.jpeg',
    './img/image-8.jpeg',
    './img/image-9.jpeg',
    './img/image-10.jpeg',  
  ];
  
  export const placeholders = [
    "Ex.: Carlos Alberto", 
    "", 
    "Ex.: Backup (suprir quedas), Peak Shaving (evitar picos de demanda), Arbitragem (economizar energia usando o BESS), Outros (não sei ao certo)", 
    "Ex.: Sim", 
    "Ex.: 0.6 MWp (fotovoltaico), com potência ativa média de 0.5 MW", 
    "Ex.: Sim", 
    "Ex.: Gerador de 500 kVA, com potência de 400 kW", 
    "Ex.: R$ 5,45 por litro", 
    "Ex.: O gerador diesel hoje é utilizado nos horários de ponta das 17h até às 20h", 
    "Ex.: A rede elétrica cai cerca de 5 vezes ao ano com duração média de 1 hora", 
    "Ex.: 380V trifásico", 
    "Ex.: Área externa de 150 m² disponível ao lado do galpão principal", 
    "Ex.: Consumo médio de 450 kW, pico de 620 kW (14h–16h).", 
    "Ex.: Sim, como sistemas de refrigeração e fornos industriais", 
    "Ex.: Até 30 milissegundos (ms)", 
    "Ex.: 150 kW de um total de 600 kW (25%)",
    "Ex.: 70% das cargas críticas são indutivas (motores, compressores etc.)",
  ];
  
   
  export const curiosidades = [
    "Você sabia? A You.On é pioneira em armazenamento de energia no Brasil.",
    "Na falta de energia, mantém sua casa ligada",
    "Segurança e conforto para sua família.",
    "Energia garantida. Negócios garantidos.",
    "Produção Infinita. 24 horas por dia.",
    "Energia Sempre: Segurança e Produtividade no Campo.",
    "Energia sustentável sem interrupções",
    "Soluções modernas para um sistema mais seguro e eficiente.",
    "Rede elétrica estabilizada 24/7",
    "Energia 100% limpa",
    "Uma nova forma de consumir energia.",
    "Sistemas modernos, design sofisticado, diversas soluções.",
    "Otimize a distribuição de energia com armazenamento avançado.",
    "Evite sobrecargas, estabilize a rede elétrica e leve energia confiável e sustentabilidade.",
    "Fizemos todo o sistema para subestação de Registro na Cidade de São Paulo.",
    "Você sabia? A You.On é pioneira em armazenamento de energia no Brasil.",
  ];
   
  export const perguntas = [
    "Digite seu nome: ",
    "Faça o Upload da sua fatura",
    "Qual o tipo de solução?",
    "Possui um sistema fotovoltaico instalado na unidade?",
    "Qual a potência instalada (MWp e MW)?",
    "Possui gerador a diesel no local?",
    "Qual a potência do gerador (kVA e kW)?",
    "Qual valor do combustível no local do Projeto (R$/L)?",
    "Qual período de utilização do gerador diesel ? (ex: H.Ponta das 18h as 21h / somente em contingencias de rede)",
    "Qual a frequencia de queda de energia proveniente da concessionária local e qual a sua duração média ?",
    "Qual a tensão do ponto de conexão onde o sistema de armazenamento de energia deverá ser instalado ?",
    "Alguma observação relevante quanto ao local de instalação, limites de espaço físico, área classificada, etc. ?",
    "Informar o perfil de carga da unidade (perfil de consumo diário ). Caso esteja no  Ambiente de Contratação Livre, pode ter acesso ao histórico SCDE (Sistema de Coleta de Dados de Energia). Enviar as informações dos últimos 12 meses.",
    "Existem cargas críticas na sua unidade que não podem parar de forma alguma ?",
    "Qual tempo máximo de comutação de On Grid para Off Grid aceitável em caso de uma queda de rede?",
    "Qual o percentual em kW dessas cargas críticas com relação à potencia total da unidade consumidora?",
    "Do total de cargas críticas, qual o percentual de cargas indutivas (motores elétricos, compressores de ar condicionado, elevadores, transformadores, etc). ?",
  ];
  