export const imagensPerguntas = [
    './img/imagem-container-verde.jpg',
    './img/youon-home.jpg',
    './img/container-cinza.jpg',
    './img/image-5.jpeg',
    './img/image-6.jpeg',
    './img/image-7.jpeg',
    './img/image-8.jpeg',
    './img/image-9.jpeg',
    './img/image-10.jpeg',  
  ];
  
  export const placeholders = [
    "Ex.: Carlos Alberto",
    "a",
    "Ex.: 1000KW",
    "Ex.: Sim",
    "Ex.: O maior excedente durante o dia é de 100KW por 2 horas.",
    "Ex.: Em anexo segue o perfil diário de consumo da planta",
    "Ex.: Sim",
    "Ex.: 40% dos 735KW totais, isto é aproximadamente 294KW.",
    "Ex.: 2 motores de 100CV (75KW) não apresentam inversores de frequência e partem diretamente na rede. Os demais são controlados por inversor de frequência.",
    "Ex.: Segue anexo lista de cargas da planta",
    "Ex.: Sim",
    "Ex.: 20 ms",
    "Ex.: Hoje temos 200KW em cargas críticas, isto é, 20% do total das cargas não podem parar.",
    "Ex.: Dos 200KW de cargas críticas, 75% são cargas indutivas, isto é, 150KW",
    "Ex.: Não",
    "Ex.: Existe uma área de 200m2 para instalação de uma planta",
    "Ex.: Modalidade A3 Verde com tarifa ponta e fora ponta.",
    "Ex.: Aparentemente existe mas não sei em quanto estimar este excedente",
    "Ex.: Sim, 250KVA em 380Vca",
    "Ex.: R$5,70 por litro",
    "Ex.: O gerador diesel hoje é utilizado nos horários de ponta das 17h até às 20h",
    "Ex.: A rede elétrica cai cerca de 5 vezes ao ano com duração média de 1 hora",
    "Ex.: Será instalado na subestação na barra de 13,8KV",
    "Ex.: 100 metros até a subestação.",
    "Ex.: O sistema deverá ser instalado em sala elétrica a ser construida pelo proponente com dimensões máximas de 10m x 20m. É uma região distante do mar e portanto sem salinidade. Entretanto a umidade na região é alta, na ordem de 95%, e não se trata de uma área classificada.",
    "Ex.: Sim, existe um superviório da empresa XXXX que deve conversar com o novo sistema de armazenamento com comunicação Modbus TCP IP.",
    "Ex.: Seguem os desenhos elétricos em anexo.",
    "Ex.: Cotar em regime turn key, o qual engloba EPC e serviços de M&M"
  ];
   
  export const curiosidades = [
    "Você sabia? A You.On é pioneira em armazenamento de energia no Brasil.",
    "a",
    "Na falta de energia, mantém sua casa ligada",
    "Segurança e conforto para sua família.",
    "Energia garantida. Negócios garantidos.",
    "Produção Infinita. 24 horas por dia.",
    "Energia Sempre: Segurança e Produtividade no Campo.",
    "Energia sustentável sem interrupções",
    "Soluções modernas para um sistema mais seguro e eficiente.",
    "Rede elétrica estabilizada 24/7",
    "Energia 100% limpa",
    "Uma nova forma de consumir energia.",
    "Sistemas modernos, design sofisticado, diversas soluções.",
    "Otimize a distribuição de energia com armazenamento avançado.",
    "Evite sobrecargas, estabilize a rede elétrica e leve energia confiável e sustentabilidade.",
    "Fizemos todo o sistema para subestação de Registro na Cidade de São Paulo.",
    "Você sabia? A You.On é pioneira em armazenamento de energia no Brasil.",
    "Na falta de energia, mantém sua casa ligada",
    "Segurança e conforto para sua família.",
    "Energia garantida. Negócios garantidos.",
    "Nossa equipe é 100% dedicada ao cliente.",
    "Produção de energia infinita para sua empresa. 24 horas por dia.",
    "Energia 100% limpa",
    "Energia sustentável sem interrupções",
    "Temos programas de fidelidade para clientes recorrentes.",
    "Soluções modernas para um sistema mais seguro e eficiente.",
    "Sistemas modernos, design sofisticado, diversas soluções.",
  ];
   
  export const perguntas = [
    "Digite seu nome: ",
    "Faça o Upload da sua fatura",
    "Qual o tipo de solução?",
    "Possui um sistema fotovoltaico instalado na unidade?",
    "Qual a potência instalada (MWp e MW)?",
    "Possui gerador a diesel no local?",
    "Qual a potência do gerador (kVA e kW)?",
    "Qual valor do combustível no local do Projeto (R$/L)?",
    "Qual período de utilização do gerador diesel ? (ex: H.Ponta das 18h as 21h / somente em contingencias de rede)",
    "Qual a frequencia de queda de energia proveniente da concessionária local e qual a sua duração média ?",
    "Qual a tensão do ponto de conexão onde o sistema de armazenamento de energia deverá ser instalado ?",
    "Alguma observação relevante quanto ao local de instalação, limites de espaço físico, área classificada, etc. ?",
    "Informar o perfil de carga da unidade (perfil de consumo diário ). Caso esteja no  Ambiente de Contratação Livre, pode ter acesso ao histórico SCDE (Sistema de Coleta de Dados de Energia). Enviar as informações dos últimos 12 meses.",
    "Existem cargas críticas na sua unidade que não podem parar de forma alguma ?",
    "Qual tempo máximo de comutação de On Grid para Off Grid aceitável em caso de uma queda de rede?",
    "Qual o percentual em kW dessas cargas críticas com relação à potencia total da unidade consumidora?",
    "Do total de cargas críticas, qual o percentual de cargas indutivas (motores elétricos, compressores de ar condicionado, elevadores, transformadores, etc). ?"
  ];
  